const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const Module = require('node:module');
const ts = require('typescript');
const {Keypair} = require('@solana/web3.js');
function compile(file,overrides={}) { const filename=path.resolve(file);const m=new Module(filename,module);m.filename=filename;m.paths=Module._nodeModulePaths(path.dirname(filename));const fallback=m.require.bind(m);m.require=n=>Object.hasOwn(overrides,n)?overrides[n]:fallback(n);m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{esModuleInterop:true,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,filename);return m.exports; }
function setup(t) {
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'market-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 const pair=Keypair.generate();const st={dir,settings:{cluster:'mainnet'},passphrase:'test-only-vault-password'};
 const wid='wallet_000001', id='dc_test_000001',remoteId='quote_000001';let q={id:remoteId,buyer_ref:id,chain:'solana',status:'reserved',user_price_total:'100000001',total_due:'100000001',topup_required:'0',expected_amount:'100000001',received_amount:'0',pay_address:Keypair.generate().publicKey.toBase58(),reserved_until:new Date(Date.now()+600000).toISOString(),items:[{wallet_id:wid,user_price:'100000001',balance:'20000000'}]};
 const calls=[],imports=[];let failCreation=false,failImport=false,failKeys=false;
 global.fetch=async(url,opts={})=>{calls.push({url,opts});if(url.endsWith('/quote')&&failCreation)throw new Error('timeout');if(url.endsWith('/keys')) {if(failKeys)throw new Error('timeout');return Response.json([{wallet_id:wid,private_key_hex:Buffer.from(pair.secretKey).toString('hex')}]);}if(url.includes('/catalog?')) return Response.json({items:[{id:wid,chain:'solana',user_price:'100000001',balance:'20000000',tier:'tier1',tx_count:20}]});return Response.json(q);};
 class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
 const api=compile('src/server/marketplace.ts',{'./api':{HttpError},'./store':{store:()=>st},'./engine':{requireUnlocked:()=>{if(!st.passphrase)throw new HttpError(423,'Vault locked');}},'./wallets':{importWallets:(lines)=>{if(failImport)throw new Error('disk unavailable');imports.push(lines);return{added:lines.length,errors:[]};}},'@/engine/solana/keys.js':{parseSolanaKey:()=>{throw new Error('unsupported');}}});
 return {api,st,q,calls,imports,pair,body:{id,walletIds:[wid],total:'100000001',consent:true},failCreation:()=>failCreation=true,failImport:(v)=>failImport=v,failKeys:()=>failKeys=true};
}
test('exact lamports and creation idempotency survive repeated requests',async t=>{const x=setup(t);const a=await x.api.reserveMarket(x.body);assert.equal(a.total,'100000001');assert.equal(a.payAddress,x.q.pay_address);await x.api.reserveMarket(x.body);assert.equal(x.calls.filter(c=>c.url.endsWith('/quote')).length,1);assert.ok(!('delivery' in a));});
test('locked vault, devnet, stale price and missing consent create no order',async t=>{const x=setup(t);await assert.rejects(x.api.reserveMarket({...x.body,consent:false}));await assert.rejects(x.api.reserveMarket({...x.body,total:'1'}),/Prices changed/);x.st.settings.cluster='devnet';await assert.rejects(x.api.reserveMarket(x.body),/mainnet/);x.st.settings.cluster='mainnet';x.st.passphrase=null;await assert.rejects(x.api.reserveMarket(x.body),/locked/);assert.equal(x.calls.filter(c=>c.url.endsWith('/quote')).length,0);});
test('ambiguous reservation is saved and never creates a second order',async t=>{const x=setup(t);x.failCreation();assert.equal((await x.api.reserveMarket(x.body)).status,'review');await x.api.reserveMarket(x.body);assert.equal(x.calls.filter(c=>c.url.endsWith('/quote')).length,1);});
test('changed selection, total or payment address suppress payment instructions',async t=>{const x=setup(t);await x.api.reserveMarket(x.body);x.q.pay_address=Keypair.generate().publicKey.toBase58();assert.equal((await x.api.refreshMarket(x.body.id)).payAddress,undefined);x.q.items[0].wallet_id='other_wallet';assert.match((await x.api.refreshMarket(x.body.id)).error,/selection/);});
test('unpaid order cannot retrieve private keys',async t=>{const x=setup(t);await x.api.reserveMarket(x.body);await assert.rejects(x.api.importMarket(x.body.id),/not confirmed/);assert.equal(x.calls.filter(c=>c.url.endsWith('/keys')).length,0);});
test('encrypted delivery recovers failed imports without re-fetching keys',async t=>{const x=setup(t);await x.api.reserveMarket(x.body);x.q.status='completed';x.q.received_amount=x.q.total_due;x.failImport(true);await assert.rejects(x.api.importMarket(x.body.id),/disk/);const saved=fs.readFileSync(path.join(x.st.dir,'marketplace-orders.json'),'utf8');assert.ok(!saved.includes(Buffer.from(x.pair.secretKey).toString('hex')));assert.ok(!('delivery' in x.api.marketHistory()[0]));x.failImport(false);const o=await x.api.importMarket(x.body.id);assert.equal(o.imported,true);assert.deepEqual(o.addresses,[x.pair.publicKey.toBase58()]);await x.api.importMarket(x.body.id);assert.equal(x.calls.filter(c=>c.url.endsWith('/keys')).length,1);assert.equal(x.imports.length,1);});
test('ambiguous one-time delivery is not fetched twice',async t=>{const x=setup(t);await x.api.reserveMarket(x.body);x.q.status='completed';x.q.received_amount=x.q.total_due;x.failKeys();await assert.rejects(x.api.importMarket(x.body.id));await assert.rejects(x.api.importMarket(x.body.id),/one-time/);assert.equal(x.calls.filter(c=>c.url.endsWith('/keys')).length,1);});

test('deposit verification settles only the saved quote, and funded orders cannot be cancelled',async t=>{const x=setup(t);await x.api.reserveMarket(x.body);await x.api.settleMarket(x.body.id);assert.equal(x.calls.filter(c=>c.url.endsWith('/quote/quote_000001/settle')).length,1);assert.equal(x.calls.filter(c=>c.url.endsWith('/keys')).length,0);x.q.received_amount='1';await assert.rejects(x.api.cancelMarket(x.body.id),/funded/);assert.equal(x.calls.filter(c=>c.url.endsWith('/cancel')).length,0);});
