"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { get, post, useGet, failureMessage } from "@/lib/api";
import { useSettings, useVault, refreshVaultDependents } from "@/lib/store";
import { marketSol, type MarketCatalog, type MarketOrder } from "@/lib/marketplace";
import { toast } from "@/components/ui";
const input = "w-full rounded-lg border border-line-100 bg-input-100 px-3 py-2 text-sm text-text-100";
const button = "rounded-lg border border-line-100 px-3 py-2 text-sm text-text-100 hover:border-accent disabled:opacity-40";
export function WalletMarketplace() {
  const catalog = useGet<MarketCatalog>("/api/marketplace", 60000);
  const history = useGet<MarketOrder[]>("/api/marketplace/orders", 10000);
  const vault = useVault(); const settings = useSettings();
  const [tier, setTier] = useState(""); const [source, setSource] = useState(""); const [persona, setPersona] = useState(""); const [zone, setZone] = useState("");
  const [min, setMin] = useState(""); const [max, setMax] = useState(""); const [selected, setSelected] = useState<Set<string>>(new Set());
  const [count, setCount] = useState(5); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [view, setView] = useState<"catalog" | "history">("catalog"); const [orderId, setOrderId] = useState<string | null>(null);
  const order = useGet<MarketOrder>(orderId ? `/api/marketplace/orders/${orderId}` : null, 10000);
  const [placed, setPlaced] = useState<MarketOrder | null>(null); const current = order.data ?? placed;
  const wallets = useMemo(() => catalog.data?.wallets ?? [], [catalog.data]);
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const filtered = useMemo(() => wallets.filter(w => (!tier || w.tier === tier) && (!source || w.source === source) && (!persona || w.persona === persona) && (!zone || w.timezone === zone) && (!min || Number(marketSol(w.price)) >= Number(min)) && (!max || Number(marketSol(w.price)) <= Number(max))).sort((a, b) => BigInt(a.price) < BigInt(b.price) ? -1 : BigInt(a.price) > BigInt(b.price) ? 1 : 0), [wallets, tier, source, persona, zone, min, max]);
  const chosen = wallets.filter(w => selected.has(w.id)); const total = chosen.reduce((n, w) => n + BigInt(w.price), BigInt(0)).toString();
  const enabled = vault.data?.unlocked && settings.data?.cluster === "mainnet";
  const choices = (key: "source" | "persona" | "timezone") => [...new Set(wallets.map(w => w[key]).filter(Boolean))].sort();
  async function reserve() {
    setBusy(true); setError("");
    try {
      const signature = chosen.map(w => w.id).sort().join(",") + ":" + total;
      let pending: { signature: string; id: string } | null = null;
      try { pending = JSON.parse(localStorage.getItem("donchain.market.reservation") || "null"); } catch {}
      const id = pending?.signature === signature ? pending.id : `dc_${crypto.randomUUID().replaceAll("-", "")}`;
      localStorage.setItem("donchain.market.reservation", JSON.stringify({ signature, id }));
      const result = await post<MarketOrder>("/api/marketplace", { id, walletIds: chosen.map(w => w.id), total, consent });
      setPlaced(result); setOrderId(result.id); history.refresh(); catalog.refresh();
    } catch (e) { setError(failureMessage(e)); } finally { setBusy(false); }
  }
  async function action(name: "import" | "cancel" | "settle") {
    if (!current) return; setBusy(true); setError("");
    try { const result = await post<MarketOrder>(`/api/marketplace/orders/${current.id}`, { action: name }); setPlaced(result); order.refresh(); history.refresh(); catalog.refresh(); if (name === "import") { refreshVaultDependents(); toast("Purchased wallets imported", "ok"); } else if (name === "cancel") { localStorage.removeItem("donchain.market.reservation"); } } catch (e) { setError(failureMessage(e)); } finally { setBusy(false); }
  }
  async function copy(value: string) { try { await navigator.clipboard.writeText(value); toast("Copied", "ok"); } catch { setError("Clipboard unavailable. Select and copy the value manually."); } }
  const paymentAvailable = current?.status === "reserved" && !current.error && current.payAddress && current.expiresAt && Date.parse(current.expiresAt) > now;
  return <div className="mx-auto max-w-[1600px] space-y-5 p-4 lg:p-6">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/portfolio" className="text-xs text-text-300">← Portfolio</Link><h1 className="mt-2 text-2xl font-semibold text-text-100">Wallet Marketplace <span className="text-sm text-accent">Solana</span></h1><p className="mt-1 text-sm text-text-300">Compare available wallets. Prices include the wallet’s native SOL balance; tokens are shown separately.</p></div><div className="flex gap-2"><button className={button} onClick={() => setView("catalog")}>Catalog</button><button className={button} onClick={() => setView("history")}>History</button><button className={button} onClick={() => { catalog.refresh(); history.refresh(); }}>Refresh</button></div></header>
    {!enabled && <p className="rounded-lg border border-line-100 p-3 text-sm text-text-300">Unlock your vault and select Solana mainnet to reserve and import wallets.</p>}
    {Boolean(error || catalog.error || order.error) && <p role="alert" className="rounded-lg border border-decrease p-3 text-sm text-decrease">{error || (catalog.error ? failureMessage(catalog.error) : failureMessage(order.error))}</p>}
    <div className="grid gap-5 lg:grid-cols-[230px_1fr]">
      <aside className="space-y-5 rounded-xl border border-line-100 p-4 text-sm"><div><h2 className="mb-2 font-semibold text-text-100">Providers</h2><div className="rounded-lg border border-accent p-2 text-accent">AnySwap · Live catalog</div>{["Husher", "Sumo", "Proxima"].map(p => <div key={p} className="mt-2 rounded-lg border border-line-100 p-2 text-text-300">{p}<span className="block text-xs">Purchase access unverified</span></div>)}</div>
      {view === "catalog" && <><label className="block text-text-300">Quality tier<select className={input} value={tier} onChange={e => setTier(e.target.value)}><option value="">All tiers</option>{[...new Set(wallets.map(w => w.tier))].map(v => <option key={v} value={v}>{v.replace("tier", "Tier ")}</option>)}</select></label>
      <label className="block text-text-300">Funding source<select className={input} value={source} onChange={e => setSource(e.target.value)}><option value="">All sources</option>{choices("source").map(v => <option key={v}>{v}</option>)}</select></label>
      <label className="block text-text-300">Persona<select className={input} value={persona} onChange={e => setPersona(e.target.value)}><option value="">All personas</option>{choices("persona").map(v => <option key={v} value={v}>{v.replaceAll("_", " ")}</option>)}</select></label>
      <label className="block text-text-300">Activity timezone<select className={input} value={zone} onChange={e => setZone(e.target.value)}><option value="">All regions</option>{choices("timezone").map(v => <option key={v}>{v}</option>)}</select></label>
      <div className="text-text-300">Price range · SOL<div className="mt-1 flex gap-2"><input aria-label="Minimum price" className={input} type="number" min="0" step="0.01" placeholder="Min" value={min} onChange={e => setMin(e.target.value)} /><input aria-label="Maximum price" className={input} type="number" min="0" step="0.01" placeholder="Max" value={max} onChange={e => setMax(e.target.value)} /></div></div>
      <button className={button} onClick={() => { setTier(""); setSource(""); setPersona(""); setZone(""); setMin(""); setMax(""); }}>Reset filters</button></>}
      <p className="text-xs text-text-300">Funding sources such as Binance are wallet history labels, not separate sellers.</p></aside>
      <section className="min-w-0 space-y-4">
      {view === "catalog" ? <><div className="flex flex-wrap items-center justify-between gap-3 text-sm text-text-300"><span>{catalog.loading ? "Loading live inventory…" : `${filtered.length} matching wallets · Lowest price first`}</span><div className="flex items-center gap-2"><input aria-label="Number of wallets" type="number" min="1" max="20" className={`${input} !w-20`} value={count} onChange={e => setCount(Math.max(1, Math.min(20, Number(e.target.value) || 1)))} /><button className={button} onClick={() => setSelected(new Set(filtered.slice(0, count).map(w => w.id)))}>Select cheapest</button><button className={button} onClick={() => setSelected(new Set())}>Clear</button></div></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(w => <button type="button" key={w.id} onClick={() => setSelected(previous => { const n = new Set(previous); if (n.has(w.id)) n.delete(w.id); else if (n.size < 20) n.add(w.id); return n; })} aria-pressed={selected.has(w.id)} className={`rounded-xl border p-4 text-left transition-colors ${selected.has(w.id) ? "border-accent bg-accent/5" : "border-line-100 bg-bg-100 hover:border-accent/50"}`}>
      <div className="flex items-start justify-between gap-2"><span className="text-xs text-text-300">AnySwap · {w.tier.replace("tier", "Tier ")}</span><span className="text-accent">{selected.has(w.id) ? "✓" : "+"}</span></div><p className="my-3 text-xl font-semibold text-text-100">{marketSol(w.price)} <span className="text-sm text-text-300">SOL</span></p><p className="text-sm capitalize text-text-100">{w.persona.replaceAll("_", " ") || "Unspecified persona"}</p><div className="mt-4 space-y-2 text-xs text-text-300"><p className="flex justify-between"><span>SOL included</span><span className="text-text-100">{marketSol(w.balance)}</span></p><p className="flex justify-between"><span>Tokens · estimated value</span><span>${w.tokensUsd.toFixed(2)}</span></p><p className="flex justify-between"><span>Funded by</span><span className="capitalize">{w.source}</span></p><p className="flex justify-between"><span>Funding date</span><span>{w.fundedAt ? new Date(w.fundedAt).toLocaleDateString() : "—"}</span></p><p className="flex justify-between"><span>Transactions · region</span><span>{w.txCount} · {w.timezone || "—"}</span></p></div></button>)}</div>
      {!catalog.loading && !filtered.length && <p className="rounded-xl border border-line-100 p-8 text-center text-text-300">No available wallets match these filters.</p>}
      <div className="rounded-xl border border-line-100 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="text-text-100">{chosen.length} selected · <strong>{marketSol(total)} SOL</strong><p className="text-xs text-text-300">Network fee is additional. No automatic payment.</p></div><button disabled={!enabled || busy || !chosen.length || !consent} onClick={reserve} className="rounded-lg bg-accent px-5 py-2 text-sm font-semibold text-white disabled:opacity-40">{busy ? "Working…" : "Reserve & review payment"}</button></div><label className="mt-4 flex items-start gap-2 text-xs text-text-300"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} /><span>I accept AnySwap’s <a href="https://app.anyswap.bot/terms-of-service" target="_blank" rel="noreferrer" className="text-accent">terms</a>, <a href="https://app.anyswap.bot/privacy-policy" target="_blank" rel="noreferrer" className="text-accent">privacy policy</a> and <a href="https://app.anyswap.bot/anti-money-policy" target="_blank" rel="noreferrer" className="text-accent">AML policy</a>. Wallet IDs are shared with the provider. The seller may retain a copy of the keys; completed purchases are final.</span></label></div></> : <div className="space-y-2">{(history.data ?? []).map(o => <button key={o.id} className={`${button} flex w-full items-center justify-between gap-3 text-left`} onClick={() => { setPlaced(o); setOrderId(o.id); }}><span>AnySwap · {o.walletIds.length} wallets<br /><span className="text-xs text-text-300">{new Date(o.createdAt).toLocaleString()}</span></span><span>{o.total ? `${marketSol(o.total)} SOL` : "—"} · {o.status}</span></button>)}{!history.data?.length && <p className="p-5 text-text-300">No purchases yet.</p>}</div>}
      {current && <div className="rounded-xl border border-accent p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold text-text-100">Order · {current.status}</h2><button className={button} onClick={async () => { try { const result = await get<MarketOrder>(`/api/marketplace/orders/${current.id}`); setPlaced(result); order.refresh(); } catch (e) { setError(failureMessage(e)); } }}>Check status</button></div><p className="mt-2 break-all text-xs text-text-300">{current.id}</p>{current.error && <p role="alert" className="mt-3 text-sm text-decrease">{current.error} Use this order’s status check before creating another reservation.</p>}
      {paymentAvailable && <div className="mt-4 space-y-3"><p className="text-sm text-text-300">Send exactly <strong className="text-text-100">{marketSol(current.total!)} SOL</strong> on <strong>Solana mainnet</strong> before {new Date(current.expiresAt!).toLocaleString()}.</p><div className="flex flex-wrap gap-2"><button className={button} onClick={() => copy(marketSol(current.total!))}>Copy amount</button><button className={`${button} break-all`} onClick={() => copy(current.payAddress!)}>{current.payAddress} · Copy</button></div><p className="text-xs text-text-300">Do not pay twice. Wait for confirmation, then import into your unlocked vault.</p><button disabled={busy || !enabled || (!!current.received && BigInt(current.received) > BigInt(0))} className={button} onClick={() => action("cancel")}>Cancel unpaid reservation</button></div>}
      {["reserved", "expired"].includes(current.status) && <button disabled={busy || !enabled} className={`${button} mt-4`} onClick={() => action("settle")}>I have sent payment · Verify deposit</button>}
      {current.status === "reserved" && !paymentAvailable && <p className="mt-3 text-sm text-text-300">Payment instructions are unavailable or expired. Check status; do not send funds to an expired reservation.</p>}
      {["settled", "completed", "paid", "delivered"].includes(current.status) && <button disabled={busy || !enabled} className={`${button} mt-4`} onClick={() => action("import")}>Import purchased wallets into vault</button>}
      {current.imported && <div className="mt-3 text-sm text-accent">Wallets imported into your vault.{current.addresses?.map(a => <p className="mt-1 break-all text-xs" key={a}>{a}</p>)}<Link href="/portfolio" className="mt-2 inline-block underline">Open portfolio</Link></div>}</div>}
      </section>
    </div>
  </div>;
}
