/** 3D icon from /public/icons/<name>.webp (generated by scripts/gen-icons.mjs). */
export type IconName =
  | "radar"
  | "dashboard"
  | "trenches"
  | "trending"
  | "launch"
  | "portfolio"
  | "rewards"
  | "settings"
  | "pumpfun"
  | "bundle"
  | "sniper"
  | "buy"
  | "volume"
  | "wash"
  | "autodump"
  | "jito";

export function Icon3D({ name, size = 20, className, glow }: { name: IconName; size?: number; className?: string; glow?: boolean }) {
  return (
    // eslint-disable-next-line @next/next/no-img-element -- static asset with alpha, served as-is
    <img
      src={`/icons/${name}.webp`}
      alt=""
      aria-hidden
      width={size}
      height={size}
      draggable={false}
      className={["shrink-0 select-none", glow ? "drop-shadow-[0_0_12px_#3b82f666]" : "", className ?? ""].join(" ")}
      style={{ width: size, height: size }}
    />
  );
}
